server:
  port: 8080
  #context-path: /a

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/seckill?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 131719
    driver-class-name: com.mysql.jdbc.Driver


mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: b2c.example.domain
  configLocation: classpath:mybatis-config.xml
logging:
  level:


